// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ChatMessage } from '../chat/chat-message';


export class MessageBatch {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MessageBatch {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMessageBatch(bb:flatbuffers.ByteBuffer, obj?:MessageBatch):MessageBatch {
  return (obj || new MessageBatch()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMessageBatch(bb:flatbuffers.ByteBuffer, obj?:MessageBatch):MessageBatch {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MessageBatch()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

messages(index: number, obj?:ChatMessage):ChatMessage|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new ChatMessage()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

messagesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

latestEventTimestamp():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startMessageBatch(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addMessages(builder:flatbuffers.Builder, messagesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, messagesOffset, 0);
}

static createMessagesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startMessagesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addLatestEventTimestamp(builder:flatbuffers.Builder, latestEventTimestamp:bigint) {
  builder.addFieldInt64(1, latestEventTimestamp, BigInt('0'));
}

static endMessageBatch(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createMessageBatch(builder:flatbuffers.Builder, messagesOffset:flatbuffers.Offset, latestEventTimestamp:bigint):flatbuffers.Offset {
  MessageBatch.startMessageBatch(builder);
  MessageBatch.addMessages(builder, messagesOffset);
  MessageBatch.addLatestEventTimestamp(builder, latestEventTimestamp);
  return MessageBatch.endMessageBatch(builder);
}
}
