syntax = "proto3";
package rpc.payment;

service PaymentService {
  rpc CreatePayment (CreatePaymentRequest) returns (PaymentReply);
  rpc GetPayment    (GetPaymentRequest)    returns (PaymentReply);
  rpc ListPayments  (ListPaymentsRequest)  returns (ListPaymentsResponse);
}

message CreatePaymentRequest {
  int64  account_id = 1;
  int64  amount = 2;
  string currency = 3;
  string product_id = 4;
  string idempotency_key = 5;
}

message GetPaymentRequest {
  int64 payment_id = 1;
  int64 account_id = 2;
}

message ListPaymentsRequest {
  int64 account_id = 1;
  int32 page = 2;
  int32 take = 3;
}

message ListPaymentsResponse {
  repeated PaymentReply payments = 1;
  int32 page = 2;
  int32 take = 3;
  int32 item_count = 4;
  int32 page_count = 5;
  bool has_previous_page = 6;
  bool has_next_page = 7;
}

message PaymentReply {
  int64  payment_id = 1;
  int64  account_id = 2;
  int64  amount = 3;
  string currency = 4;
  string product_id = 5;
  string status = 6;
}
